"""Create tables AFD, AP e MT

Revision ID: e7a20bdc9db3
Revises: 
Create Date: 2025-02-05 21:59:33.030739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a20bdc9db3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deterministic_finite_automata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('states', sa.JSON(), nullable=True),
    sa.Column('input_symbols', sa.JSON(), nullable=True),
    sa.Column('transitions', sa.JSON(), nullable=True),
    sa.Column('initial_state', sa.String(), nullable=True),
    sa.Column('final_states', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deterministic_finite_automata_id'), 'deterministic_finite_automata', ['id'], unique=False)
    op.create_index(op.f('ix_deterministic_finite_automata_name'), 'deterministic_finite_automata', ['name'], unique=True)
    op.create_table('pushdown_automata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('states', sa.JSON(), nullable=True),
    sa.Column('input_symbols', sa.JSON(), nullable=True),
    sa.Column('stack_symbols', sa.JSON(), nullable=True),
    sa.Column('transitions', sa.JSON(), nullable=True),
    sa.Column('initial_state', sa.String(), nullable=True),
    sa.Column('initial_stack_symbol', sa.String(), nullable=True),
    sa.Column('final_states', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pushdown_automata_id'), 'pushdown_automata', ['id'], unique=False)
    op.create_index(op.f('ix_pushdown_automata_name'), 'pushdown_automata', ['name'], unique=True)
    op.create_table('turing_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('states', sa.JSON(), nullable=True),
    sa.Column('input_symbols', sa.JSON(), nullable=True),
    sa.Column('tape_symbols', sa.JSON(), nullable=True),
    sa.Column('transitions', sa.JSON(), nullable=True),
    sa.Column('initial_state', sa.String(), nullable=True),
    sa.Column('blank_symbol', sa.String(), nullable=True),
    sa.Column('final_states', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turing_machines_id'), 'turing_machines', ['id'], unique=False)
    op.create_index(op.f('ix_turing_machines_name'), 'turing_machines', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turing_machines_name'), table_name='turing_machines')
    op.drop_index(op.f('ix_turing_machines_id'), table_name='turing_machines')
    op.drop_table('turing_machines')
    op.drop_index(op.f('ix_pushdown_automata_name'), table_name='pushdown_automata')
    op.drop_index(op.f('ix_pushdown_automata_id'), table_name='pushdown_automata')
    op.drop_table('pushdown_automata')
    op.drop_index(op.f('ix_deterministic_finite_automata_name'), table_name='deterministic_finite_automata')
    op.drop_index(op.f('ix_deterministic_finite_automata_id'), table_name='deterministic_finite_automata')
    op.drop_table('deterministic_finite_automata')
    # ### end Alembic commands ###
